services:
  postgres:
    image: postgres:17
    container_name: postgres-local
    environment:
      POSTGRES_DB: scrapper
      POSTGRES_USER: scrapper
      POSTGRES_PASSWORD: scrapper
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  redis-data:
  postgres_data:
