server:
  port: 8082

spring:
  application:
    name: scrapper

app:
  stackoverflow:
    key: ${STACKOVERFLOW_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
    access-token: ${STACKOVERFLOW_ACCESS_KEY} # Use env variable. DO NOT KEEP TOKEN HERE
    base-url: https://api.stackexchange.com/2.3
  github:
    token: ${GITHUB_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    base-url: https://api.github.com

bot:
  base-url: http://localhost:8081

scheduler:
  interval: 60000

