server:
  port: 8081

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  application:
    name: bot
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092,localhost:9094,localhost:9095}

app:
  telegram:
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    update-listener-sleep: 1s
    debug: false
  kafka:
    topic: link-updates
    retry:
      attempts: 3

scrapper:
  base-url: ${SCRAPPER_URL:http://localhost:8082}
  connect-timeout: 3s
  read-timeout: 5s
  retryable-statuses: [429, 500, 502, 503, 504]

resilience4j:
  retry:
    instances:
      scrapperRetry:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - backend.academy.linktracker.bot.application.exception.RetryableException
        ignore-exceptions:
          - backend.academy.linktracker.bot.application.exception.ScrapperClientException
